### ISSUE TITLE
Compatibility with EtherIP library

### ISSUE THREAD

**Issue by johanfforsberg** [pjkundert/cpppo#1]
Hi,

this looks like a nice project and I started looking into whether it might be useful for writing tests for an EtherIP communication project we have. We're using a C EtherIP library from http://ics-web.sns.ornl.gov/kasemir/etherip/ and it's working fine for communicating with our Allen-Bradley PLCs.

However, I have trouble getting that library to talk to the cpppo test server and I'm wondering if this should even be expected to work. This is what I'm doing:

Starting the test server:
```
# python -m cpppo.server.enip --print SCADA=INT[1]
```
and then I run the test program included with the EtherIP library:
```
# ./ether_ip_test -v 10 -i 127.0.0.1 -p 44818 SCADA
```
The result is "No response" and the server prints out the following traceback:
```
11-11 15:36:36.861     7f610f4ef700 enip.lgx ERROR    process    EtherNet/IP CIP error at 0 total bytes:
''
-^ (byte 0)

11-11 15:36:36.861     7f610f4ef700 enip.srv ERROR    enip_srv   Failed request: {
    "request.addr": [
        "127.0.0.1", 
        59815
    ], 
    "request.enip.command": 4, 
    "request.enip.length": 0, 
    "request.enip.options": 0, 
    "request.enip.sender_context.input": "array('c', 'Funstuff')", 
    "request.enip.session_handle": 0, 
    "request.enip.status": 0
}
11-11 15:36:36.862     7f610f4ef700 enip.srv ERROR    enip_srv   EtherNet/IP error at 24 total bytes:
'\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Funstuff\x00\x00\x00\x00'
-------------------------------------------------------------------------^ (byte 24)

Failed with exception:
Traceback (most recent call last):
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/server/enip/main.py", line 664, in enip_srv
    if enip_process( addr, data=data, **kwds ):
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/server/enip/logix.py", line 681, in process
    source.chain( data.request.enip.input )
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/dotdict.py", line 201, in __getattr__
    raise AttributeError( str( exc ))
AttributeError: 'input'


11-11 15:36:36.863     7f610f4ef700 network  WARNING  run        enip_srv server failure: 'input'
Traceback (most recent call last):
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/server/network.py", line 131, in run
    super( server_thread, self ).run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/server/enip/main.py", line 664, in enip_srv
    if enip_process( addr, data=data, **kwds ):
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/server/enip/logix.py", line 681, in process
    source.chain( data.request.enip.input )
  File "/home/johfor/.local/lib/python2.7/site-packages/cpppo/dotdict.py", line 201, in __getattr__
    raise AttributeError( str( exc ))
AttributeError: 'input'
```

**Comment by pjkundert** [comment]
I have implemented ListServices in version 3.3.0; these tests now pass.  Thanks so much for the report!  Let me know if you see anything else, or if you need a hand integrating your solution.
