### ISSUE TITLE
Client import problem 

### ISSUE THREAD

**Issue by tavora-lucas** [pjkundert/cpppo#114]
When I try to import client, like this:
```python
from cpppo.server.enip import client
``` 

I get this:
```
Traceback (most recent call last):
  File "c:\Users\itsmemario\Documents\Python\eip\main.py", line 4, in <module>
    from cpppo.server.enip import client
  File "c:\Users\itsmemario\Documents\Python\venv\Lib\site-packages\cpppo\__init__.py", line 29, in <module>
    from .automata import *
  File "c:\Users\itsmemario\Documents\Python\venv\Lib\site-packages\cpppo\automata.py", line 33, in <module>
    from . import misc
  File "c:\Users\itsmemario\Documents\Python\venv\Lib\site-packages\cpppo\misc.py", line 221, in <module>
    change_function( __normal, co_filename=logging._srcfile )
  File "c:\Users\itsmemario\Documents\Python\venv\Lib\site-packages\cpppo\misc.py", line 180, in change_function
    modi_code                   = types.CodeType( *modi_args )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
```

**Comment by beenje** [comment]
This is a Python 3.11 issue (should be the same on Linux). Same as #111 

There is a fix in https://github.com/pjkundert/cpppo/pull/110 (but still not merged).
