### ISSUE TITLE
Number of tags supported on the server?

### ISSUE THREAD

**Issue by MaticPogacnik** [pjkundert/cpppo#89]
Hi,

I tried to load ~ 500 different tags (NOT array) to the server, and I hit an undesirable limitations:
* Simulator startup is very slow, to set up 500 tags it takes ~ 20-30 seconds.
* If I try to pull only one of  values with the `python -m cpppo.server.enip.client -r 1000 Beamline_Type`, CPU usage goes to 100% and sometimes the client stops with an Empty Response Error.

Is there a limitations how many tags are supported inside the simulator or is this possibly a bug?

Thanks

**Comment by MaticPogacnik** [comment]
This is the error on the client:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1699, in <module>
    sys.exit( main() )
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1680, in main
    fragment=fragment, printing=printing, timeout=timeout )
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1444, in process
    transactions                = list( self.results( operations=operations, **kwds ))
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1436, in results
    for idx,dsc,req,rpy,sts,val in self.operate( operations, **kwds ):
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1431, in operate
    for idx,dsc,req,rpy,sts,val in harvested:
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1321, in validate
    for index,descr,request,reply,status,val in harvested:
  File "/home/devman/dev/cpppo/venv_cpppo/lib64/python3.6/site-packages/cpppo-4.0.6-py3.6.egg/cpppo/server/enip/client.py", line 1308, in pipeline
    complete, requests )
AssertionError: Communication ceased before harvesting all pipeline responses: 505/507
```
